# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b95e5039f6f36036214cfc22df968e3ba95a87bd5681f7b4acca81d0761398aa53b47961edd0ffe631d46072a88811060dd12af6540bbc1b90dce8f911c7611

test:
  secret_key_base: f57f197cef21d34615174413fb2ffe0fd11f77653bdce33cb81f52423fef19e970183d377a86dcfb42926fbf0383f64fdd23de609dd94beab2d6d147ab7d53ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
